solution status: optimal solution found
objective value:                                 3360
COL158                                              1 	(obj:0)
COL020                                              1 	(obj:0)
COL023                                              1 	(obj:0)
COL061                                              1 	(obj:0)
COL078                                              1 	(obj:0)
COL102                                              1 	(obj:0)
COL117                                              1 	(obj:0)
COL131                                              1 	(obj:0)
COL133                                              1 	(obj:0)
COL148                                              1 	(obj:0)
COL149                                              1 	(obj:0)
COL151                                              1 	(obj:0)
COL153                                              1 	(obj:0)
COL155                                              1 	(obj:0)
COL156                                              1 	(obj:0)
COL160                                           3360 	(obj:1)
