NAME  soplex.bas
 XL BAL.3EBW       BAL...BW
 XL BN4.3EBW       BHC...BW
 XL BP8.3EBW       BLC...BW
 XL BTO.3EBW       BLV...BW
 XL BLC.3PBW       BP8...BW
 XL BN4.3PBW       BTO...BW
 XL BP8.3PBW       B3E...BW
 XL BAL.3RBW       B3P...BW
 XL BHC.3RBW       B3R...BW
 XL BLC.3RBW       B3E.VOBW
 XL BLV.3RBW       B3P.VOBW
 XL BN4.3RBW       B3R.VOBW
 XL BP8.3RBW       HML.3EBW
 XL M3..3TBW       HRM.3EBW
 XL QPB73EBW       HML.3RBW
 XL QVO73EBW       HMM.3RBW
 XL QVO73PBW       HRM.3RBW
 XL QPB73RBW       NOI.3EBW
 XL QVO73RBW       NOI.3PBW
 XL WMO73EBW       NOI.3RBW
 XL WRO73EBW       WMO.3PBW
 XL WMO73PBW       WRO.3PBW
 XU WRO73PBW       XRV.3EBW
 XU WMO73RBW       XRV.3PBW
 XU WRO73RBW       XRV.3RBW
ENDATA
